# This is a basic workflow to help you get started with Actions

name: Deploy docs

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: Get docs requirements
        run: python -m pip install -r doc/requirements.txt

      - name: Install the package
        run: python -m pip install .

      - name: Build docs
        run: sphinx-build doc/ doc/_build/html

      - uses: actions/upload-pages-artifact@v2
        with:
          path: doc/_build/html
